# Generated by Django 3.1.13 on 2021-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210905_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionsession',
            name='questions',
            field=models.ManyToManyField(related_name='user_questions', to='questions.Question'),
        ),
    ]
