# Generated by Django 3.1.13 on 2021-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210906_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionsession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
