# Generated by Django 3.1.13 on 2021-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_userquestionsession_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionsession',
            name='answers',
            field=models.JSONField(default=list),
        ),
    ]
